### PR TITLE
Optimize the code flow in parser.c

### PR DESCRIPTION
**Pull request by tliston**
Several of the if statements in the parser were sub-optimal. I've
reformatted them to produce more efficient code. Based on testing,
it appears that the new version of the parser is approximately 15%
faster.

### CODE REVIEW

**Comment by rondilley** [comment]
Looks good, nice percentage improvement!

**Comment by tliston** [comment]
It should directly transfer over to the other two projects... they appear
to use the same parser.

-TL

**Comment by rondilley** [comment]
They do and I will drop this update into them.

**Comment by tliston** [comment]
Good. Keeps me from having to deal with Git.

I can optimize complex chains of boolean if-then statements, but Git makes
my brain hurt.

🤣🤣🤣

-TL

**Comment by rondilley** [comment]
They have not really nice GUI interfaces for Git (to make it simpler on your brain) . . . =P

**Pull request merged**
